# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.TextField()),
                ('decoded_data', models.TextField()),
                ('issued_date', models.DateTimeField()),
                ('airport_id', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'ordering': ('airport_id',),
            },
        ),
    ]
