# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metar',
            old_name='decoded_data',
            new_name='decoded_metar',
        ),
        migrations.RenameField(
            model_name='metar',
            old_name='issued_date',
            new_name='issued_at',
        ),
        migrations.RenameField(
            model_name='metar',
            old_name='raw_data',
            new_name='raw_metar',
        ),
    ]
