# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metars', '0002_auto_20161122_0801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metar',
            options={'ordering': ('raw_metar',)},
        ),
        migrations.RemoveField(
            model_name='metar',
            name='airport_id',
        ),
        migrations.RemoveField(
            model_name='metar',
            name='issued_at',
        ),
    ]
